name: deploy to aliyun oss

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 使用 node:10
      - name: Setup Node and cache
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn' # or yarn
      # Yarn install
      - name: Install dependencies
        run: yarn install
      - name: Build and deploy
        run: yarn build
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      - name: Sync file to oss
        run: ossutil sync dist oss://${{ secrets.OSS_KEY_BUCKET }}/ --delete --force
